Repository NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-iOS, pull requests merged in 2024-05, with the labels that each got.

#2 [SETTING] 프로젝트 초기 세팅 (#1)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOBANK-iOS/KAKAOBANK-iOS/AppDelegate.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Assets.xcassets/AccentColor.colorset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Assets.xcassets/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Base.lproj/LaunchScreen.storyboard
  KAKAOBANK-iOS/KAKAOBANK-iOS/Base.lproj/Main.storyboard
  KAKAOBANK-iOS/KAKAOBANK-iOS/Info.plist
  KAKAOBANK-iOS/KAKAOBANK-iOS/SceneDelegate.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/ViewController.swift
Labels: ⚙️Setting, 🐰희슬

#12 [FIX] 이미지 에셋 이슈 해결 (#11)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
Labels: 🐰희슬, 🩹 Fix

#19 [FEAT] 상단 계좌 & 잔액 UI 구현 (#14
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Extension/UIFont+.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Extension/UILabel+.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/ViewControllers/BankAccountViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/BankAccountNaviBar.swift
Labels: 🛠️Feat, 🫧민서

#22 [FEAT] 입출금 내역 tableView & sticky header 구현 (#20)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS/Application/SceneDelegate.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Extension/UIFont+.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Extension/UILabel+.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/BankBookInfo/btn_backleading_gray_ios.imageset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/BankBookInfo/btn_backleading_gray_ios.imageset/btn_backleading_ios.svg
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/BankBookInfo/btn_filter_ios.imageset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/BankBookInfo/btn_filter_ios.imageset/btn_filter_ios.svg
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/BankBookInfo/btn_frontleading_gray_ios.imageset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/BankBookInfo/btn_frontleading_gray_ios.imageset/btn_backleading_iods.svg
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/BankBookInfo/btn_searchpre_ios.imageset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/BankBookInfo/btn_searchpre_ios.imageset/btn_searchpre_ios.svg
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Cells/BankAccountTableViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Models/BankAccountModel.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/ViewControllers/BankAccountViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/BankAccountNaviBar.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/StickyHeaderView.swift
Labels: 🛠️Feat, 🫧민서

#28 [Fix] addSubViews/addArrangedSubviews 적용 (#27)
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Cells/BankAccountTableViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/ViewControllers/BankAccountViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/StickyHeaderView.swift
Labels: 🫧민서, 🩹 Fix

#25 [Fix] 코딩 컨벤션에 맞게 이슈 #10 코드를 수정(#24)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOBANK-iOS/KAKAOBANK-iOS/Application/SceneDelegate.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Cells/CollectionViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/CollectionViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/UITabBarController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AdView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AddButtonView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AddView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/HeaderView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MainAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MeetingAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MessageBoxView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SavingsView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SecondAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SimpleBarView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/ThirdAccountView.swift
Labels: 🥯서영, 🩹 Fix

#30 [FEAT] '은행 선택' 뷰 UI 구현 (#18)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/SelectBank/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/SelectBank/btn_searchpre_ios.imageset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/SelectBank/btn_searchpre_ios.imageset/btn_searchpre_ios.svg
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/Cells/BankListCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/ViewControllers/SelectBankViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/Views/BottomSheetView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/Views/DimmedView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/Views/SegmentView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/Views/SelectBankHeaderView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Models/BankBookModel.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/ViewControllers/TransferViewController.swift
Labels: 🛠️Feat, 🐰희슬

#32 [Feat] Navigation Tab Bar 기능 구현(#26)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS/Application/SceneDelegate.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/Home/btn_myaccount_and.imageset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/Home/icn_bankimg2_ios.imageset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/Home/icn_star_ios.imageset/Contents.json
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/Home/icn_star_ios.imageset/icn_star_and.svg
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Resources/Assets.xcassets/Home/icn_star_ios.imageset/icn_star_ios.svg
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Main/ViewControllers/MainViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Cells/CollectionViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Cells/TipsCollectionViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/TipsModel.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainTabBarController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/TipsViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/UITabBarController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AddButtonView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AddView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/HeaderView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MainAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MeetingAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MessageBoxView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SavingsView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SecondAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SimpleBarView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/ThirdAccountView.swift
Labels: 🛠️Feat, 🥯서영

#43 [Fix] 길이, 정렬, 패딩, 스크롤바, 아이콘 수정(#40)
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainTabBarController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/TipsViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AddButtonView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MainAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MeetingAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MessageBoxView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SavingsView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SecondAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/ThirdAccountView.swift
Labels: 🥯서영, 🩹 Fix

#44 [FEAT] 화면 연결 (#42)
  KAKAOBANK-iOS/KAKAOBANK-iOS/Application/SceneDelegate.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Extension/UIFont+.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Extension/UILabel+.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Cells/BankAccountTableViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/ViewControllers/BankAccountViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/BankAccountNaviBar.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/BankAccountUpperView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainTabBarController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MainAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/ViewControllers/SelectBankViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/Views/BottomSheetView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/ViewControllers/TransferViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Views/TransferNaviBar.swift
Labels: 🛠️Feat, 🐰희슬

#46 [FIX] 계좌 내역 뷰에 하단 탭바 추가 (#45)
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/ViewControllers/BankAccountViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainTabBarController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainViewController.swift
Labels: 🫧민서, 🩹 Fix

#51 [SETTING] 서버 통신 관련 세팅 (#50)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Settings/Config.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Settings/Info.plist
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/BaseService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/BaseTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/MoyaLoggingPlugin.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/NetworkResult.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/NetworkService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Transfer/DTO/GetRecentTransferResponseDTO.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Transfer/TransferService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Transfer/TransferTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Models/AccountInfoModel.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/ViewControllers/TransferViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Views/AccountInfoView.swift
Labels: ⚙️Setting, 🐰희슬

#53 [FEAT] 즐겨찾기 등록 서버 통신 (#52)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/BaseResponseDTO.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/NetworkService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Bookmark/BookmarkService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Bookmark/BookmarkTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Transfer/TransferTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Cells/RecentTransferCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Models/AccountInfoModel.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/ViewControllers/TransferViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Views/AccountInfoView.swift
Labels: 🛠️Feat, 🐰희슬, 🌐Network

#54 [Feat] 내 계좌 정보 조회 API 연동 (#47)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/NetworkService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MyAccount/DTO/GetMyAccountResponse.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MyAccount/MyAccountService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MyAccount/MyAccountTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/ViewControllers/BankAccountViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/BankAccountNaviBar.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/BankAccountUpperView.swift
Labels: 🛠️Feat, 🫧민서, 🌐Network

#56 [Feat] 메인 페이지, 이체 화면 API 총 두 개 연결(#49)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/NetworkService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MainAccount/DTO/GetMainAccountResponse.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MainAccount/MainAccountService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MainAccount/MainAccountTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Transfer/TransferService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Transfer/TransferTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MainAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SecondAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/ThirdAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Cells/RecentTransferCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Models/AccountInfoModel.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/ViewControllers/TransferViewController.swift
Labels: 🛠️Feat, 🥯서영, 🌐Network

#60 [FIX] 뷰 디테일 수정 (#59)
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MonthlyPayment/DTO/GetPaymentResponse.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Cells/BankAccountTableViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/ViewControllers/BankAccountViewController.swift
Labels: 🫧민서, 🩹 Fix

#63 [CHORE] 컨벤션에 맞춰 코드 정리 (#58)
  KAKAOBANK-iOS/KAKAOBANK-iOS.xcodeproj/project.pbxproj
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Transfer/DTO/GetRecentTransferResponse.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Transfer/TransferService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Cells/MyAccountCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/ViewControllers/TransferViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Views/AccountInfoView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Views/InputAccountButton.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Views/SectionHeaderView.swift
Labels: 🐰희슬, 🧹 Chore

#62 [Fix] 분기처리 수정, 프린트문 및 주석 제거(#61)
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/NetworkService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MainAccount/MainAccountService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Cells/TipsCollectionViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainTabBarController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/TipsViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AddButtonView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/HeaderView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MainAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MeetingAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MessageBoxView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SavingsView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SecondAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SimpleBarView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/ThirdAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Cells/RecentTransferCell.swift
Labels: 🥯서영, 🩹 Fix

#67 [FIX] 슬라이드 로직 수정 (#64)
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/ViewControllers/SelectBankViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/Views/BottomSheetView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/Transfer/Cells/RecentTransferCell.swift
Labels: 🐰희슬, 🩹 Fix

#69 [CHORE] 최종 코드 정리 (#68)
  KAKAOBANK-iOS/KAKAOBANK-iOS/Global/Extension/UILabel+.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/Base/BaseService.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MonthlyPayment/PaymentTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Network/MyAccount/MyAccountTargetType.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Cells/BankAccountTableViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/ViewControllers/BankAccountViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/BankAccountNaviBar.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/BankAccountUpperView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/BankAccount/Views/StickyHeaderView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Cells/TipsCollectionViewCell.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainTabBarController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/MainViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/ViewControllers/TipsViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AddButtonView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/AddView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/HeaderView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MainAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MeetingAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/MessageBoxView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SavingsView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SecondAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/SimpleBarView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/MainPage/Views/ThirdAccountView.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/ViewControllers/SelectBankViewController.swift
  KAKAOBANK-iOS/KAKAOBANK-iOS/Presentation/SelectBank/Views/SegmentView.swift
Labels: 🐰희슬, 🧹 Chore
